var = input('Insira qualquer coisa: ')
print(f'É ALFANUMÉRICA? {var.isalnum()}')
print(f'É ALFABÉTICA? {var.isalpha()}')
print(f'É ASCII? {var.isascii()}')
print(f'É DÍGITO? {var.isdigit()}')
print(f'É TODA MINÚSCULA? {var.islower()}')
print(f'É DECIMAL? {var.isdecimal()}')
print(f'É NOME DE VARIÁVEL VÁLIDO? {var.isidentifier()}')
print(f'É NUMÉRICA? {var.isnumeric()}')
print(f'É PRINTÁVEL? {var.isprintable()}')
print(f'É ESPAÇO? {var.isspace()}')
print(f'É TITULARIZADA? {var.istitle()}')
print(f'É TODA MAIÚSCULA? {var.isupper()}')
input()